config/routes.rb
Rails.application.routes.draw do
  root to: 'links#index'
  get    'signup'    => 'users#new',        as: :signup
  get    'signin'    => 'sessions#new',     as: :signin
  get    'users/:id' => 'users#show',       as: :user
  get    'tags/:tag' => 'links#index',      as: :tag
  post   'users'     => 'users#create',     as: :users
  post   'signin'    => 'sessions#create'
  delete 'signout'   => 'sessions#destroy', as: :signout
  resources :links
end

app/models/link.rb
class Link < ActiveRecord::Base
  strip_attributes
  validates :url, presence: true, url: true
  acts_as_taggable
  belongs_to :user

  private
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :downcase_email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       length: { maximum: 30 },
                       format: { with: /\A[a-zA-Z0-9_-]+\z/ }
  validates :email,    presence: true, uniqueness: { case_sensitive: false },
                       format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 6 }
  has_secure_password

  has_many :links, dependent: :destroy

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include LinksHelper
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :not_signed_in?

  def index
    if params[:tag]
      @links = current_user.links.tagged_with(params[:tag])
    else
      @links = current_user.links.order('id DESC')
    end
  end

  def new
    @link = Link.new
  end

  def create
    @link = current_user.links.build(link_params)
    @link.title, @link.url = get_title_and_url(@link.url) if @link.valid?
    if @link.save
      flash[:success] = "New link successfully added"
      redirect_to edit_link_path(@link)
    else
      render 'new'
    end
  end

  def edit
    @link = current_user.links.find_by(id: params[:id])
  end

  def update
    @link = current_user.links.find_by(id: params[:id])
    if @link.update_attributes(link_params)
      flash[:success] = "Link successfully updated"
      redirect_to root_path
    else
      flash.now[:error] = "Form contains some errors"
      render 'update'
    end
  end

  def destroy
    current_user.links.destroy(params[:id])
    redirect_to root_path
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :about, :tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :signed_in?, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Welcome back, #{user.username}!"
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:error] = "Invalid combination Email/Password"
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in?, only: [:new, :create]

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome aboard, #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:error] = "Form contains some errors"
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                                    :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper

  def get_title_and_url(url)
    @page = MetaInspector.new(url)
    return @page.title.strip, @page.url
  end
end

# begin
#   @page = MetaInspector.new(url)
# rescue Faraday::ConnectionFailed
#   flash.now[:error] = "Connection Failed"
#   redirect_to new_link_path
# else
#   return @page.title, @page.url
# end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def signed_in?
    redirect_to root_path if logged_in?
  end

  def not_signed_in?
    redirect_to signin_path unless logged_in?
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Pinx
    = stylesheet_link_tag    'application', media: 'all',
                                            'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      div = link_to 'Pinx', root_path, id: 'logo'
      div.nav
        ul
          - unless logged_in?
            li = link_to 'Sign in',  signin_path
          - else
            li = link_to 'Add link', new_link_path, class: 'new_link_btn'
            li = link_to 'Sign out', signout_path, method: :delete

    section.main
      - flash.each do |key, value|
        div class="flash flash-#{key}" == value

      == yield

app/views/links/edit.html.slim
h1 Edit link

= simple_form_for @link do |f|
  = f.input :url,      placeholder: "Site url",         label: false
  = f.input :title,    placeholder: "Site title",       label: false
  = f.input :about,    placeholder: "Site description", label: false
  = f.input :tag_list, placeholder: "Tags (separated by commas)",
                       label: false, value: @link.tag_list.to_s
  = f.submit "Save link"

app/views/links/index.html.slim
- @links.each do |link|
  div.bookmark id="link_#{link.id}"
    div.link = link_to link.title, link.url
    div.options
        = link_to 'Edit',   edit_link_path(link)
        = link_to 'Delete', link_path(link), method: :delete,
                  data: { confirm: "Are you sure?" }
    div.about
      - if link.about
        = link.about
    div.tags
      - if link.tag_list.any?
         ' Tags:
         = raw link.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')

div#tag_cloud
  - tag_cloud @links.tag_counts, %w[s m l] do |tag, css_class|
    = link_to tag.name, tag_path(tag.name), class: css_class
    '

app/views/links/new.html.slim
h1 Add link

= simple_form_for @link do |f|
  = f.input :url, placeholder: "Site url", label: false
  = f.submit "Add link"

app/views/users/new.html.slim
h1 Sign up

div.signup
  = simple_form_for @user do |f|
    = f.input :username, placeholder: "Username", label: false
    = f.input :email, placeholder: "Email", label: false
    = f.input :password, placeholder: "Password", label: false
    = f.input :password_confirmation, placeholder: "Confirm password", label: false
    = f.submit "Sign up"
  = link_to 'Already have an account', signin_path

app/views/users/show.html.slim
h1 = @user.username